### ISSUE TITLE
Supports Babylon.js 6.x

### ISSUE THREAD

**Issue by il-m-yamagishi** [virtual-cast/babylon-vrm-loader#101]
- https://github.com/BabylonJS/Babylon.js/releases/tag/6.0.0

**Comment by Spencer17x** [comment]
Is it difficult to upgrade to 6.x? Is there any plan to support this part

**Comment by Spencer17x** [comment]
I have completed the upgrade to support Babylon.js 6.x, and migrated to my warehouse under https://github.com/Spencer17x/arca/tree/main/packages/awesome-babylonjs/babylonjs-vrm-loader, please Is it allowed to migrate to this warehouse? If so, I have noted in the readme that the code comes from babylon-vrm-loader, and the same is true for babylon-mtoon-material.

**Comment by yamayuski** [comment]
- please see https://github.com/il-m-yamagishi/babylon-vrm-loader/issues/1
