### ISSUE TITLE
v3 Roadmap

### ISSUE THREAD

**Issue by il-m-yamagishi** [virtual-cast/babylon-vrm-loader#104]
- [ ] #103
- [ ] #101
- [ ] #75 
- [ ] #28 
- [ ] #25 
- [ ] #23 

NOTICE: Supports VRM 1.0 #64 is not part of v3, it will be processed another time.

**Comment by yamayuski** [comment]
- please see https://github.com/il-m-yamagishi/babylon-vrm-loader/issues/1
