### ISSUE TITLE
VRM without vertex Normal attribute will unexpected behaviour.

### ISSUE THREAD

**Issue by iCyP** [virtual-cast/babylon-vrm-loader#32]
https://twitter.com/iCyP/status/1163691288849338368 のVroidHubよりDLできるモデルについての問題です。
法線属性をgltfのjsonから削除したVRMを読み込ませると、TSOでは新ﾋﾞｭｰﾜモデルの大部分が表示されず、サンプルページ（ https://codepen.io/akai_inu/pen/zQXyxL?editors=1010 ）ではロードが終了しません。
期待される動作は、uniVRM0.53およびTSO旧ビューワにおける表示になります。

**Comment by il-m-yamagishi** [comment]
https://github.com/virtual-cast/babylon-mtoon-material/releases/tag/v1.8.5 こちらの修正で表示されるようになります。

babylon.js の _StandardMaterial_ の仕様として「法線がない場合は Fragment Shader 上で算出する」という仕組みがあるので、 UniVRM と表示は異なります。

babylon-vrm-loader への適用及び TSO ビューアへの適用は後日となりますのでご了承ください。

**Comment by iCyP** [comment]
承知いたしました。ありがとうございます。
