### ISSUE TITLE
MToon: Texture transform seems not to be handled properly

### ISSUE THREAD

**Issue by FMS-Cat** [virtual-cast/babylon-vrm-loader#5]
UniVRMに付属するMToonでは、すべてのテクスチャのSTに対して
`materialProperties[i].vectorProperties._MainTex` を適用する実装となっていますが、
一部テクスチャに対して適切にSTが実装されていないようです。

以下はテスト用のモデルです。
`_MainTex` ・ `_ShadeTexture` ・ `_EmissionMap` に対して同様の形状のテクスチャが入っていますが、
`_MainTex` 以外の2つのテクスチャについて、STの当たり方がデフォルトのままになっている気がします。

[color-space-test.zip](https://github.com/virtual-cast/babylon-vrm-loader/files/3190071/color-space-test.zip)

![image](https://user-images.githubusercontent.com/7824814/57906227-3dee8900-78b4-11e9-92f9-da7b9b1f13ea.png)

こちらのSandboxで確認しました: https://virtual-cast.github.io/babylon-vrm-loader/

環境はWindows 10・Chrome 74です。

**Comment by FMS-Cat** [comment]
https://github.com/virtual-cast/babylon-vrm-loader/blob/d4b005f72a672ab147e464201eaa98f984e2341f/src/vrm-material-generator.ts#L112-L117

このあたりでしょうか？今後仕様がこっちに変わる可能性もあり、悩ましいですね……

**Comment by il-m-yamagishi** [comment]
状況理解しました。ひとまず現状の MToon 仕様に出来るだけ忠実にしたいので、修正します。

**Comment by il-m-yamagishi** [comment]
修正しました。ご報告ありがとうございます。

![image](https://user-images.githubusercontent.com/15116901/57909451-c7568900-78bd-11e9-906b-fe968a402e05.png)
