### ISSUE TITLE
Why the morphTarget is an array ?

### ISSUE THREAD

**Issue by sknightq** [virtual-cast/babylon-vrm-loader#65]
I want to replace [three-vrm](https://github.com/pixiv/three-vrm/) with babylon-vrm-loader, but I have confusion about the morph target:
In three-vrm, change blendeshape using as following ([demo](https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/examples/blendshapes.html)):
```
// set value
currentVrm.blendShapeProxy.setValue( THREE.VRMSchema.BlendShapePresetName.A, 0.5 + 0.5 * s );
currentVrm.blendShapeProxy.setValue( THREE.VRMSchema.BlendShapePresetName.BlinkL, 0.5 - 0.5 * s );
// get value
currentVrm.blendShapeProxy.getValue( THREE.VRMSchema.BlendShapePresetName.A);
currentVrm.blendShapeProxy.getValue( THREE.VRMSchema.BlendShapePresetName.BlinkL);
```
In babylon-vrm-loader, I think using **morphing** method can set value. 
```
currentVrm.morphing('A', 1)
currentVrm.morphing('Blink_L', 1)
```
However, I don't know how to get the **morphTarget** value because the target is an array. And the array has the same object as this:
![Screenshot from 2022-01-07 13-27-05](https://user-images.githubusercontent.com/8033144/148496391-f53393d5-4cba-4272-9c4f-90306bbb6b72.png)

three-vrm get value method [source code](https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/src/blendshape/VRMBlendShapeProxy.ts)

**Comment by il-m-yamagishi** [comment]
There are `MorphTarget`s per `Mesh.morphTargetManager`, so we need to set influence every related meshes.

Currently, there is no API to retrieve runtime morphTarget value.

I think it is good to add API like `VRMManager.getMorphing(label: string): Nullable<number>`.

**Comment by sknightq** [comment]
@il-m-yamagishi Thanks for your reply! 
But how to calculate the result of influence value?
Just compare the counts of value **1** and value **0**, or if has **0** then return **0**, or other rules?
I'm not familiar with the VRM.

**Comment by sknightq** [comment]
> There are `MorphTarget`s per `Mesh.morphTargetManager`, so we need to set influence every related meshes.
What's more, the related meshes are all same in this array.
I think you shouldn't push an existing morph target into the Array.
